laguage: python
sudo: required
python:
  - "3.4"
  - "3.5"
#command to install dependencies
install:
  - "sudo pip install -r requirements-tests.txt"
#command to run tests
script: "python manage.py test"