language: python
python:
  - "3.4"
  - "3.5"

#To go headless
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
#command to install dependencies
install:
  - "pip install -r requirements-tests.txt"


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

 #command to run tests
script: "python manage.py test"